# Análisis de Precios en Mercamadrid: Volatilidad, Estacionalidad y Riesgo en la Planificación de Compras

El presente estudio pretende identificar patrones estacionales, volatilidad y evolución histórica de precios en productos listados en Mercamadrid, entre los años 2021 y 2025 inclusive, con el fin de aportar información accionable que permita tomar mejores decisiones de compra anticipando meses de mayor riesgo presupuestario.

El análsis se plantea desde la perspectiva de un *Analista de Datos Junior* laborando para una empresa de distribución de alimentos, utilizando datos públicos y técnicas exploratorias para simular un caso realista.

Los dataframes utilizados en este cuaderno se encuentran disponibles de forma gratuita en https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/

In [36]:
#Importando librerías requeridas

import pandas as pd
import math
import glob

import seaborn as sns
import matplotlib.pyplot as plt

#Recuperando los archivos históricos
files = glob.glob(r"C:\Users\allan\OneDrive\Desktop\Documentos\Mis Análsis\Mercamadrid\data\volpre*.csv")


dfs = [pd.read_csv(f, encoding="ISO-8859-1", sep=';', decimal=',') for f in files]
df=pd.concat(dfs, ignore_index=True)

#Examinando la estructura básica
print (df.head())
print (df.info())

  Fecha Desde  Fecha Hasta  Código Variedad             Descripción Variedad  \
0    20210101     20210131          CA 0101   VACUNO CANAL
1    20210101     20210131          CA 0101   VACUNO CANAL
2    20210101     20210131          CA 0101   VACUNO CANAL
3    20210101     20210131          CA 0101   VACUNO CANAL
4    20210101     20210131          CA 0101   VACUNO CANAL

   Origen     Descripción Origen       Kilos  Precio Más Frecuente  \
0     005   AVILA                  000002220                  4,27
1     008   BARCELONA              000066910                  4,29
2     010   CACERES                001327305                  4,29
3     015   LA CORUÑA              000052640                   4,3
4     017   GERONA                 000010440                  4,28

   Precio Máximo  Precio Mínimo
0           4,27           4,27
1           4,31           4,27
2           4,31           4,27
3           4,31           4,27
4           4,28           4,28
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187011 entries, 0 to 187010
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Fecha Desde            187011 non-null  object
 1    Fecha Hasta           187011 non-null  object
 2    Código Variedad       187011 non-null  object
 3    Descripción Variedad  187011 non-null  object
 4    Origen                187011 non-null  object
 5    Descripción Origen    187011 non-null  object
 6    Kilos                 187011 non-null  object
 7    Precio Más Frecuente  187011 non-null  object
 8    Precio Máximo         187011 non-null  object
 9    Precio Mínimo         187011 non-null  object
dtypes: object(10)
memory usage: 14.3+ MB
None

In [37]:
#Normalizando nombres de columnas
df.columns = df.columns.str.replace(' ','')
df.columns

Index(['FechaDesde', 'FechaHasta', 'CódigoVariedad', 'DescripciónVariedad',
       'Origen', 'DescripciónOrigen', 'Kilos', 'PrecioMásFrecuente',
       'PrecioMáximo', 'PrecioMínimo'],
      dtype='object')

In [38]:
#Limpieza de datos tipo fecha

df["FechaHasta"] = df["FechaHasta"].astype('str').str.strip();

#Ajustando formato de fechas
df["FechaDesde"]=pd.to_datetime(df["FechaDesde"],format="%Y%m%d", errors="coerce");
df["FechaHasta"]=pd.to_datetime(df["FechaHasta"],format="%Y%m%d", errors="coerce");

In [39]:
#Cuantificando valores nulos en el dataset

total_rows = df.shape[0]
missing_dates = df[df["FechaDesde"].isna() | df["FechaHasta"].isna()].shape[0];

md_percentage = (missing_dates / total_rows)*100
print(f"Total Missing: {missing_dates}, Total Rows: {total_rows} --Missing Percentage: {(md_percentage):.2f}%--")

Total Missing: 52, Total Rows: 187011 --Missing Percentage: 0.03%--

## Eliminación de datos faltantes

Dada su naturaleza; el presente estudio requiere que los datos a considerar contengan campos de fecha válidos. 

Considerando que, según el cálculo anterior, solo un 0.03% de los registros no posee una fecha válida, se ha decidido prescindir de dichos datos y eliminarlos en pro de la consistencia del dataset.

In [22]:
#Eliminando datos nulos
df = df.dropna()

#Comprobando la existencia de nulos en el dataset actualizado
df.isna().sum().sort_values(ascending=False)

FechaDesde             0
FechaHasta             0
CódigoVariedad         0
DescripciónVariedad    0
Origen                 0
DescripciónOrigen      0
Kilos                  0
PrecioMásFrecuente     0
PrecioMáximo           0
PrecioMínimo           0
dtype: int64

## Ajuste de campos de precio

Los datasets en su formato original presentan precios con espacios vacíos y decimales separados por ','; 
por lo que se procede con los ajustes necesarios para su adecuado procesamiento según el código descrito a continuación.

In [23]:
#Convirtiendo precios de tipo string a tipo float
cols=["PrecioMáximo","PrecioMínimo","PrecioMásFrecuente"]

#Reemplazando ',' por '.' para la separación de decimales
df[cols]=(
    df[cols].apply(
        lambda col:col
        .str.strip()
        .str.replace(',','.',regex=False)
        .astype(float)
    )
) 

#Verificando los cambios aplicados
df.head()

,FechaDesde,FechaHasta,CódigoVariedad,DescripciónVariedad,Origen,DescripciónOrigen,Kilos,PrecioMásFrecuente,PrecioMáximo,PrecioMínimo
0,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,005,AVILA,000002220,4.27,4.27,4.27
1,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,008,BARCELONA,000066910,4.29,4.31,4.27
2,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,010,CACERES,001327305,4.29,4.31,4.27
3,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,015,LA CORUÑA,000052640,4.30,4.31,4.27
4,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,017,GERONA,000010440,4.28,4.28,4.28

## Filtrado de registros mínimos

Con el fin de realizar un análisis consistente que permita detectar tendencias de manera más certera, 
se ha decidido enfocar el estudio únicamente en aquellos productos para los cuales existan datos por al menos 24 meses.

El código necesario se muestra a continuación.

In [42]:
# Definición del umbral y filtrado de registros
product_counts = df["DescripciónVariedad"].value_counts()
min_required = 24
 
df = df[df["DescripciónVariedad"].isin(product_counts[product_counts>=min_required].index)]

df.head()

,FechaDesde,FechaHasta,CódigoVariedad,DescripciónVariedad,Origen,DescripciónOrigen,Kilos,PrecioMásFrecuente,PrecioMáximo,PrecioMínimo
0,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,005,AVILA,000002220,"4,27","4,27","4,27"
1,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,008,BARCELONA,000066910,"4,29","4,31","4,27"
2,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,010,CACERES,001327305,"4,29","4,31","4,27"
3,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,015,LA CORUÑA,000052640,"4,3","4,31","4,27"
4,2021-01-01,2021-01-31,CA 0101,VACUNO CANAL,017,GERONA,000010440,"4,28","4,28","4,28"

In [25]:
# Exportación del dataset limpio
output_path = "dataset_limpio.csv" 
df.to_csv(output_path, index=False, encoding="utf-8")